server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service-root
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
      # routes:
      #   - id: customer-service
      #     uri: lb://CUSTOMER-SERVICE
      #     predicates:
      #       - Path=/api/v1/customers,/api/v1/customers/**

      #   - id: account-service
      #     uri: lb://ACCOUNT-SERVICE
      #     predicates:
      #       - Path=/api/v1/accounts/**

      #   - id: credit-service
      #     uri: lb://CREDIT-SERVICE
      #     predicates:
      #       - Path=/api/v1/credits/**

      #   - id: credit-card-service
      #     uri: lb://CREDIT-CARD-SERVICE
      #     predicates:
      #       - Path=/api/v1/credit-cards/**

      #   - id: movement-service
      #     uri: lb://MOVEMENT-SERVICE
      #     predicates:
      #       - Path=/api/v1/movements/**

      #   - id: report-service
      #     uri: lb://REPORT-SERVICE
      #     predicates:
      #       - Path=/api/v1/reports/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted
    health:
      access: unrestricted