server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditcarddb

customer-service:
  base-url: http://localhost:8081

logging:
  level:
    root: INFO
    com.bank.creditcard: DEBUG