server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb

logging:
  level:
    root: INFO
    com.bank.customer: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: INFO